<?php

/**
 * @file
 * Hook implementations for this module.
 */

use Drupal\Core\Entity\ContentEntityType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Language\LanguageInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\path_alias\PathAliasInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function domain_unique_path_alias_entity_presave(EntityInterface $entity) {
  if ($entity instanceof PathAliasInterface) {
    // Get domains configuration.
    $options = \Drupal::entityTypeManager()
      ->getStorage('domain')
      ->loadOptionsList();

    // Get domain_id from get request param.
    $helper = \Drupal::service('domain_unique_path_alias.helper');
    $domain_id = $helper->getDomainIdByRequest();

    // Get domain_id from field_domain_source field.
    if (empty($domain_id) || !in_array($domain_id, $options)) {
      // Get field_domain_source data if a new translation.
      $node = \Drupal::routeMatch()->getParameter('node');

      // Get node from path_alias path.
      if (!$node instanceof NodeInterface) {
        $path = explode("/", $entity->getPath());
        if (
          isset($path[1], $path[2])
          && $path[1] === 'node'
          && is_numeric($path[2])
        ) {
          $node = Node::load($path[2]);
        }
      }

      if ($node instanceof NodeInterface) {
        $langcode = \Drupal::languageManager()
          ->getCurrentLanguage(LanguageInterface::TYPE_CONTENT)->getId();
        $langcode = $entity->get('langcode')->getString() ?? $langcode;
        $translation_languages = $node->getTranslationLanguages();
        if (in_array($langcode, array_keys($translation_languages))) {
          $domain_id = $helper->getDomainIdFromEntity($node);
        }
      }
    }

    // Set domain_id to path_alias entity.
    if (!empty($domain_id)) {
      /** @var \Drupal\path_alias\Entity\PathAlias $entity */
      $entity->set('domain_id', $domain_id);
    }
  }
  elseif ($entity instanceof NodeInterface) {
    // Get domain_id from entity.
    $helper = \Drupal::service('domain_unique_path_alias.helper');
    $node_domain_id = $helper->getDomainIdFromEntity($entity);
    if (!empty($node_domain_id)) {
      $path_alias = \Drupal::entityTypeManager()
        ->getStorage('path_alias')
        ->loadByProperties([
          'path' => '/node/' . $entity->id(),
          'langcode' => $entity->language()->getId(),
        ]);
      if ($path_alias) {
        /** @var PathDrupal\path_alias\PathAliasInterface $path_alias */
        $path_alias = reset($path_alias);
        $path_alias_domain_id = $path_alias->get('domain_id')->getString();
        if ($node_domain_id != $path_alias_domain_id) {
          $path_alias->set('domain_id', $node_domain_id);
          $path_alias->save();
        }
      }
    }
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function domain_unique_path_alias_entity_base_field_info(ContentEntityType $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'path_alias') {
    $fields['domain_id'] = BaseFieldDefinition::create('string')
      ->setLabel('Domain Id')
      ->setDescription('Domain identification.');
  }

  return $fields;
}

/**
 * Implements hook_validation_constraint_alter().
 */
function domain_unique_path_alias_validation_constraint_alter(array &$definitions) {
  if (isset($definitions['UniquePathAlias'])) {
    $definitions['UniquePathAlias']['class'] = '\\Drupal\\domain_unique_path_alias\\Plugin\\Validation\\Constraints\\DomainUniquePathAliasConstraint';
  }
}
