<?php

/**
 * @file
 */

use Drupal\Component\Utility\DeprecationHelper;

/**
 * @file
 * Install, update, and uninstall functions for domain_unique_path_alias.
 *
 * @ingroup domain_unique_path_alias
 */

/**
 * Implements hook_install().
 *
 * Add domain ids to existing aliases.
 */
function domain_unique_path_alias_install($is_syncing) {
  /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager */
  $entity_type_manager = \Drupal::entityTypeManager();
  /** @var \Drupal\domain_unique_path_alias\DomainUniquePathAliasHelper $path_alias_helper */
  $path_alias_helper = \Drupal::service('domain_unique_path_alias.helper');
  $path_alias_storage = $entity_type_manager->getStorage('path_alias');
  $aliases = $path_alias_storage->getQuery()
    ->notExists('domain_id')
    ->accessCheck(FALSE)
    ->execute();
  foreach ($aliases as $alias) {
    $path_alias = $path_alias_storage->load($alias);
    $path = $path_alias->getPath();
    $domain_id = $path_alias_helper->getPathDomainId($path);
    if (!empty($domain_id)) {
      $path_alias->set('domain_id', $domain_id);
      $path_alias->save();
    }
  }
}

/**
 * Implements hook_uninstall().
 *
 * Core does not properly purge field provided by configuration entities.
 * There are a few related issues and @todo notices in core to this effect.
 * Instead, we handle field purges ourselves.
 */
function domain_unique_path_alias_uninstall() {
  // Do a pass of purging on deleted Field API data, if any exists.
  $limit = \Drupal::config('field.settings')->get('purge_batch_size');
  DeprecationHelper::backwardsCompatibleCall(\Drupal::VERSION, '11.4.0', fn() => \Drupal::service('Drupal\Core\Field\FieldPurger')->purgeBatch($limit), fn() => field_purge_batch($limit));
  \Drupal::entityTypeManager()->clearCachedDefinitions();
}
